
version: 2

models:
  - name: games
    description: "A fact table of all NHL season games and recorded measures"

  - name: teams
    description: "A fact table of all NHL teams and their season statistics"

  - name: seasonal_metrics_agg
    description: "A fact table that brings together both regular season games and team statistics to date"
