version: 2

sources:
  - name: raw
    database: "NHL_STATS"
    schema: "RAW"
    tables:
      - name: nhl_api_reg_schedules
      - name: nhl_api_playoff_schedules
      - name: nhl_api_seasons
      - name: nhl_api_teams
      - name: team_stats