{{ config 
    (
        alias = 'teams',
        materialized = 'incremental', 
        incremental_strategy = 'delete+insert'
    )
}}


WITH teams AS (
    SELECT 
        CASE WHEN UPPER(TEAM) LIKE '%DIVISION%' THEN NULL ELSE TEAM END AS TEAM,
        CASE WHEN UPPER(GP) LIKE '%DIVISION%' THEN NULL ELSE GP END AS GP,
        CASE WHEN UPPER(OVERALL_WINS) LIKE '%DIVISION%' THEN NULL ELSE OVERALL_WINS END AS OVERALL_WINS,
        CASE WHEN UPPER(OVERALL_LOSSES) LIKE '%DIVISION%' THEN NULL ELSE OVERALL_LOSSES END AS OVERALL_LOSSES,
        CASE WHEN UPPER(OVERTIME_LOSSES) LIKE '%DIVISION%' THEN NULL ELSE OVERTIME_LOSSES END AS OVERTIME_LOSSES,
        CASE WHEN UPPER(TOTAL_POINTS) LIKE '%DIVISION%' THEN NULL ELSE TOTAL_POINTS END AS TOTAL_POINTS,
        CASE WHEN UPPER(POINTS_PERCENTAGE) LIKE '%DIVISION%' THEN NULL ELSE POINTS_PERCENTAGE END AS POINTS_PERCENTAGE,
        CASE WHEN UPPER(GOALS_FOR) LIKE '%DIVISION%' THEN NULL ELSE GOALS_FOR END AS GOALS_FOR,
        CASE WHEN UPPER(GOALS_AGAINST) LIKE '%DIVISION%' THEN NULL ELSE GOALS_AGAINST END AS GOALS_AGAINST,
        CASE WHEN UPPER(HOCKEY_REFERENCE_SRS) LIKE '%DIVISION%' THEN NULL ELSE HOCKEY_REFERENCE_SRS END AS HOCKEY_REFERENCE_SRS,
        CASE WHEN UPPER(STRENGTH_OF_SCHEDULE) LIKE '%DIVISION%' THEN NULL ELSE STRENGTH_OF_SCHEDULE END AS STRENGTH_OF_SCHEDULE,
        CASE WHEN UPPER(POINTS_PERCENTAGE_IN_REGULATION) LIKE '%DIVISION%' THEN NULL ELSE POINTS_PERCENTAGE_IN_REGULATION END AS POINTS_PERCENTAGE_IN_REGULATION,
        CASE WHEN UPPER(WINS_IN_REGULATION) LIKE '%DIVISION%' THEN NULL ELSE WINS_IN_REGULATION END AS WINS_IN_REGULATION,
        CASE WHEN UPPER(REGULATION_RECORD) LIKE '%DIVISION%' THEN NULL ELSE REGULATION_RECORD END AS REGULATION_RECORD,
        updated_at, 
        unique_key
    FROM {{ source('raw', 'team_stats') }}
) 
SELECT * 
FROM TEAMS
WHERE 
    TEAM IS NOT NULL AND
    GP IS NOT NULL AND
    OVERALL_WINS IS NOT NULL AND
    OVERALL_LOSSES IS NOT NULL AND
    OVERTIME_LOSSES IS NOT NULL AND
    TOTAL_POINTS IS NOT NULL AND
    POINTS_PERCENTAGE IS NOT NULL AND
    GOALS_FOR IS NOT NULL AND
    GOALS_AGAINST IS NOT NULL AND
    HOCKEY_REFERENCE_SRS IS NOT NULL AND
    STRENGTH_OF_SCHEDULE IS NOT NULL AND
    POINTS_PERCENTAGE_IN_REGULATION IS NOT NULL AND
    WINS_IN_REGULATION IS NOT NULL AND
    REGULATION_RECORD IS NOT NULL 

{% if is_incremental() %}
    AND unique_key not in ( select unique_key from {{ this }})
{% endif %}
